In [75]:
import numpy as np
import math

In [76]:
input_path='inputFloyd.txt'

In [77]:
def readData():
    data=[]
    with open(input_path) as file:
        content = file.readlines()
    for index,lines in enumerate (content):
        content[index]=lines.split()
    square=int(content[0][0])
    content=content[1:]
    return square,content

In [78]:
square,content=readData()

In [79]:
dTable = np.empty((square,square))
dTable[:]= math.inf
sTable = np.empty((square,square))
sTable[:]= math.inf

In [80]:
for i in range(0,square):
    sTable[:,i]=i+1
    s

In [81]:
for data in content:
    dTable[int(data[0])-1][int(data[1])-1]=data[2]

In [82]:
for i in range(0,square):
    print("\nIteration ke-"+str(i+1))
    for k in range(0,square):
        for l in range(0,square):
                if((k!=i or l!=i)and(k!=l)):
                    compare=dTable[k,i]+dTable[i,l]
                    if((compare<dTable[k,l])):
                        dTable[k,l]=compare
                        sTable[k,l]=i+1
    print('D Table: \n',dTable)
    print('S Table: \n',sTable)


Iteration ke-1
D Table: 
 [[inf  3. 10. inf inf]
 [ 3. inf 13.  5. inf]
 [10. 13. inf  6. 15.]
 [inf  5.  6. inf  4.]
 [inf inf inf  4. inf]]
S Table: 
 [[1. 2. 3. 4. 5.]
 [1. 2. 1. 4. 5.]
 [1. 1. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]

Iteration ke-2
D Table: 
 [[inf  3. 10.  8. inf]
 [ 3. inf 13.  5. inf]
 [10. 13. inf  6. 15.]
 [ 8.  5.  6. inf  4.]
 [inf inf inf  4. inf]]
S Table: 
 [[1. 2. 3. 2. 5.]
 [1. 2. 1. 4. 5.]
 [1. 1. 3. 4. 5.]
 [2. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]

Iteration ke-3
D Table: 
 [[inf  3. 10.  8. 25.]
 [ 3. inf 13.  5. 28.]
 [10. 13. inf  6. 15.]
 [ 8.  5.  6. inf  4.]
 [inf inf inf  4. inf]]
S Table: 
 [[1. 2. 3. 2. 3.]
 [1. 2. 1. 4. 3.]
 [1. 1. 3. 4. 5.]
 [2. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]

Iteration ke-4
D Table: 
 [[inf  3. 10.  8. 12.]
 [ 3. inf 11.  5.  9.]
 [10. 11. inf  6. 10.]
 [ 8.  5.  6. inf  4.]
 [12.  9. 10.  4. inf]]
S Table: 
 [[1. 2. 3. 2. 4.]
 [1. 2. 4. 4. 4.]
 [1. 4. 3. 4. 4.]
 [2. 2. 3. 4. 5.]
 [4. 4. 4. 4. 5.]]

Iteration ke-5
D Ta